name       : gnome-screensaver
version    : 3.6.1
release    : 14
source     :
    - git|https://github.com/getsolus/budgie-screensaver.git : 8aa17131cdfb327ca8b1f73273665a9d9a6cf98d
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
component  : desktop.gnome
summary    : GNOME Screensaver
description: |
    gnome-screensaver is a screen saver and locker that aims to have simple, sane, secure defaults and be well integrated with the desktop.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(x11)
    - gnome-common
environment: |
    export CFLAGS="$CFLAGS -Wno-deprecated -Wno-deprecated-declarations"
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    # Kill autostart
    rm -rf $installdir/etc/xdg
    install -d $installdir/usr/share/defaults
    mv $installdir/etc $installdir/usr/share/defaults/etc/
