name       : budgie-screensaver
version    : '4.0'
release    : 19
source     :
    - https://getsol.us/sources/budgie-screensaver-v4.0.tar.xz : dde83f355e549b5f6290655f33acd910d2febbb8fd974f922b14814054f80f49
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
homepage   : https://github.com/getsolus/budgie-screensaver
component  : desktop.gnome
summary    : Budgie Screensaver is a fork of gnome-screensaver intended for use with Budgie Desktop and is similar in purpose to other screensavers such as MATE Screensaver.
description: |
    Budgie Screensaver is a fork of gnome-screensaver intended for use with Budgie Desktop and is similar in purpose to other screensavers such as MATE Screensaver.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(x11)
    - gnome-common
replaces   :
    - gnome-screensaver
environment: |
    export CFLAGS="$CFLAGS -Wno-deprecated -Wno-deprecated-declarations"
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Kill autostart
    rm -rf $installdir/etc/xdg
    install -d $installdir/usr/share/defaults
    mv $installdir/etc $installdir/usr/share/defaults/etc/
