name       : gnome-screensaver
version    : 3.6.1
release    : 6
source     :
    - git|https://github.com/solus-project/budgie-screensaver.git : f2609ad80224c3a1119338c818793539b43a01d2
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.gnome
summary    : GNOME Screensaver
description: |
    gnome-screensaver is a screen saver and locker that aims to have simple, sane, secure defaults and be well integrated with the desktop. It is designed to support:
    * the ability to lock down configuration settings
    * translation into many languages
    * user switching
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - gnome-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    # Kill autostart
    rm -rf $installdir/etc/xdg
