name       : gnome-screensaver
version    : 3.6.1
release    : 8
source     :
    - git|https://github.com/solus-project/budgie-screensaver.git : b38c83f4d7d985093b978d318cb983d39c5d0285
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
component  : desktop.gnome
summary    : GNOME Screensaver
description: |
    gnome-screensaver is a screen saver and locker that aims to have simple, sane, secure defaults and be well integrated with the desktop. It is designed to support:
    * the ability to lock down configuration settings
    * translation into many languages
    * user switching
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(x11)
    - gnome-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    # Kill autostart
    rm -rf $installdir/etc/xdg
