name       : gnome-screensaver
version    : 3.6.1
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-screensaver/3.6/gnome-screensaver-3.6.1.tar.xz : f39b78d4f7fed748c7f0a31d694112fb907c6d3c4e63db22eb858df07e962cd0
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.gnome
summary    : GNOME Screensaver
description: |
    gnome-screensaver is a screen saver and locker that aims to have simple, sane, secure defaults and be well integrated with the desktop. It is designed to support:
    * the ability to lock down configuration settings
    * translation into many languages
    * user switching
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # Kill autostart
    rm -rf $installdir/etc/xdg
