name       : budgie-screensaver
version    : '5.0'
release    : 20
source     :
    - https://github.com/BuddiesOfBudgie/budgie-screensaver/releases/download/v5.0/budgie-screensaver-v5.0.tar.xz : 611969a9f53e5d3148cad7445e95c94bfff6ea61c2f339969ecb5d9b51f6b871
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
homepage   : https://github.com/getsolus/budgie-screensaver
component  : desktop.gnome
summary    : Budgie Screensaver is a fork of gnome-screensaver intended for use with Budgie Desktop and is similar in purpose to other screensavers such as MATE Screensaver.
description: |
    Budgie Screensaver is a fork of gnome-screensaver intended for use with Budgie Desktop and is similar in purpose to other screensavers such as MATE Screensaver.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnomekbdui)
    - pkgconfig(x11)
    - gnome-common
replaces   :
    - gnome-screensaver
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Kill autostart
    rm -rf $installdir/etc/xdg
    install -d $installdir/usr/share/defaults
    mv $installdir/etc $installdir/usr/share/defaults/etc/
